# Default server configuration.
host: 127.0.0.1
mongo_db: mongodb://localhost:27017/angel
port: 3000
jwt_secret: "31F4406237f806335SM8B468BYP0L653"
github:
  id: $GITHUB_ID
  secret: $GITHUB_SECRET
  redirect_uri: http://localhost:3000/auth/github/callback