description: "An easily-extensible web server framework in Dart."
homepage: "https://github.com/angel-dart/angel"
name: "pairy_server"
publish_to: "none"
dependencies: 
  angel_auth: "^1.1.0-alpha"
  angel_configuration: "^1.1.0-alpha"
  angel_cors: "^1.0.0"
  angel_framework: "^1.1.0-alpha"
  angel_jael: "^1.0.0-alpha"
  angel_serialize: "^1.0.0-alpha"
  angel_static: "^1.3.0-alpha"
  angel_validate: "^1.0.0"
dev_dependencies: 
  angel_hot: "^1.1.0-alpha"
  angel_serialize_generator: "^1.0.0-alpha"
  angel_test: "^1.1.0-alpha"
  build_runner: "^0.5.0"
  console: "^2.2.4"
  grinder: "^0.8.0"
  test: "^0.12.13"
environment: 
  sdk: ">=1.19.0"
transformers: 
  - "angel_configuration"
