description: An easily-extensible web server framework in Dart.
homepage: https://github.com/angel-dart/angel
name: pairy_server
publish_to: none
dependencies:
  angel_auth: ^1.1.0
  angel_configuration: ^1.1.0
  angel_cors: ^1.0.0
  angel_framework: ^1.1.0
  angel_jael: ^1.0.0
  angel_mongo: ^1.0.0
  angel_security: ^1.0.0
  angel_static: ^1.3.0
  angel_validate: ^1.0.0
  oauth2:
    git: https://github.com/thosakwe/oauth2.git
  pairy:
    path: ../pairy
dev_dependencies:
  angel_hot: ^1.1.0
  angel_test: ^1.1.0
  console: ^2.2.4
  test: ^0.12.13
